[package]
name = "using_pure_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cadcad_rs"

[dependencies]
rand = "0.8.4"